djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from leads.views import LeadListView, LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing_page'),
    path('leads/', include('leads.urls', namespace="leads")),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  

leads/urls.py
from django.urls import path
from .views import (
    LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView,LeadDeleteView
) 


app_name = "leads"


urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete', LeadDeleteView.as_view(), name='lead-delete'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),

]   

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey("Agent", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
class Agent(models.Model):
    user = models.OneToOneField("User", on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email
    

leads/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Lead

User = get_user_model()

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
        )



class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model=User
        fields=("username",)
        field_classes = {'username':UsernameField}

leads/views.py
from django.shortcuts import render, redirect, reverse
from django.core.mail import send_mail
from django.http import HttpResponse
from django.views import generic 
from .models import Lead, Agent
from .forms import LeadModelForm


class LandingPageView(generic.TemplateView):
    template_name = "landing.html"

class LeadListView(generic.ListView):
    template_name = "leads/lead_list.html"
    queryset= Lead.objects.all()
    context_object_name = "leads"


class LeadDetailView(generic.DetailView):
    template_name ="leads/lead_detail.html"
    queryset =  Lead.objects.all()
    context_object_name ="lead"

class LeadCreateView(generic.CreateView):
    template_name ="leads/lead_create.html"
    form_class =  LeadModelForm

    def get_success_url(self):
        return reverse("leads:lead-list")  
    
    def form_valid(self, form):
        send_mail(
            subject="A lead has been created",
            message="Go to the site to see the new lead",
            from_email="test@test.com",
            recipient_list =["perrybates@bates.com"]
        )
        return super(LeadCreateView, self).form_valid(form)   
 

class LeadUpdateView(generic.UpdateView):

    template_name = "leads/lead_update.html"
    queryset =  Lead.objects.all() 
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("leads:lead-list")
    
class LeadDeleteView(generic.DeleteView):
    template_name="leads/lead_delete.html"
    queryset =  Lead.objects.all() 

    def get_success_url(self):
        return reverse("leads:lead-list")

leads/templates/leads/lead_create.html
{% extends 'base.html' %}

{% block content %}


<a href="/leads">Go back to leads </a>
    <hr>
    <h1>Create a new lead</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}
    

leads/templates/leads/lead_delete.html
{% extends 'base.html' %}

{% block content %}


<a href="/leads">Go back to leads </a>
    <hr>
    <h1>Are you sure you have to delete this lead?</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}
    

leads/templates/leads/lead_detail.html
{% extends 'base.html' %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
          <div class="flex mb-4">
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
            
            <a href="{% url 'leads:lead-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update Details</a>
          </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900">{{lead.age}}</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Location</span>
            <span class="ml-auto text-gray-900">Dummy location</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Cell phone</span>
            <span class="ml-auto text-gray-900">+233 508 9201</span>
          </div>
          <div class="flex">
            <a href ="{% url 'leads:lead-delete' lead.pk %}" class="flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete {{lead.first_name }}</a>
          </div> 
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section> 
    
{% endblock content %}
    

leads/templates/leads/lead_list.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-400 bg-white body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="py-6 flex justify-between item-center border-b border-gray-200 w-full mb-6">
                <div><h1 class="text-4xl text-black">Leads </h1></div>
                <div>
                    <a href="{% url 'leads:lead-create'%}">Create a new lead</a>
                </div>
            </div> 
            
            
            <div class="flex flex-wrap -m-4">
                {% for lead in leads %}
                    <div class="p-4 lg:w-1/2 md:w-full">
                        <div class="flex border-2 rounded-lg border-gray-800 p-8 sm:flex-row flex-col">
                            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-gray-800 text-green-400 flex-shrink-0">
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                                </svg>
                            </div>
                            <div class="flex-grow">
                                <h2 class="text-black text-lg title-font font-medium mb-3">{{lead.first_name}} {{ lead.last_name}}</h2>
                                <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
                                <a href="{% url 'leads:lead-detail' lead.pk%}" class="mt-3 text-green-400 inline-flex items-center">
                                    View this lead
                                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
</section>

  {% endblock content %}

    

leads/templates/leads/lead_update.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
        <div class="container px-5 py-24 mx-auto">
            <div class="lg:w-4/5 mx-auto flex flex-wrap">
                    <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
                            <div class="flex mb-4">
                                    <a href="{% url 'leads:lead-detail' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                                      Overview
                                    </a>
                                    
                                   
                                    <a href="{% url 'leads:lead-update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                                        Update Details
                                    </a>
                            </div>
                            <form method="post"> 
                                {% csrf_token %}
                                {{form.as_p}}
                                <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" type="submit">Submit Update</button>
                            </form>
                            
                    </div>
                <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
            </div>
        </div>
</section> 

{% endblock content %}
    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com" rel="stylesheet"></script>
    <title>DJCRM</title>
    <link rel="{% static 'css/styles.css' %}" href="#">
</head>
<body>
    <div class="max-w-7xl mx-auto">
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
    </div>
    
</body>
</html> 

templates/landing.html
{% extends 'base.html'%}

 {% block content %}
 <section class="text-gray-400 bg-white-900 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-black">CRM built with Django</h1>
        <p class="leading-relaxed mb-8">The CRM helps you manage your leads</p>
        <div class="flex justify-center">
          <button class="inline-flex text-white bg-yellow-500 border-0 py-2 px-6 focus:outline-none hover:bg-yellow-600 rounded text-lg">Button</button>
          <button class="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-gray rounded text-lg">Button</button>
        </div>
      </div>
    </div>
  </section>
 {% endblock content %}

templates/navbar.html
<header class="text-gray-400 bg-white-900 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a class="flex title-font font-medium items-center text-white mb-4 md:mb-0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-black p-2 bg-yellow-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">AgentCRM</span>
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-black">Leads</a>
      </nav>
      <a href="#" class="inline-flex items-center bg-gray-800 border-0 py-1 px-3 focus:outline-none hover:bg-gray-700 rounded text-base mt-4 md:mt-0">Login
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
    </a>
    </div>
  </header>